### ISSUE TITLE
Do you think we have create the mockup of the page contribution ?

### ISSUE THREAD

**Issue by ndufreche** [backbee/blogbee#3]
ping @eric-chau, @mickaelandrieu, @fkroockmann, @crouillon, @hbaptiste.

Actually we have 5 pages mockup :
* Home / Category
* Article
* Author
* Author edition
* login

Do you think we have create the mockup of the page contribution ?

To vote :
* for usefull :+1:
* for useless :-1:

**Comment by eric-chau** [comment]
What do you mean by page contribution?

**Comment by ndufreche** [comment]
@eric-chau Article page + bb toolbar
In my opinion is not useful.
The contribution is directly in front and we don't have to design it.

**Comment by eric-chau** [comment]
Yeah I agree with it, i don't think this is useful too.

**Comment by mickaelandrieu** [comment]
@ndufreche, Next time ping @backbee/core-team :p
